{{- if and (eq .Values.etl.mode "stream") (eq .Values.etl.kafka.strimzi_enabled true) }}

apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: {{ .Values.etl.kafka.topics.blocks.name | quote }}
  labels:
    strimzi.io/cluster: {{ .Values.etl.kafka.cluster_name }}
spec:
  replicas: {{ .Values.etl.kafka.topics.blocks.replicas | quote }}
  partitions: {{ .Values.etl.kafka.topics.blocks.partitions | quote }}
  config:
    retention.ms: {{ .Values.etl.kafka.topics.blocks.retention.ms | quote }}
    retention.bytes: {{ .Values.etl.kafka.topics.blocks.retention.bytes | quote }}
    segment.bytes: 1073741824
    cleanup.policy: {{ .Values.etl.kafka.topics.blocks.cleanup.policy | quote }}
    min.cleanable.dirty.ratio: 0.5
    preallocate: true

---

apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: {{ .Values.etl.kafka.topics.transactions.name | quote }}
  labels:
    strimzi.io/cluster: {{ .Values.etl.kafka.cluster_name }}
spec:
  replicas: {{ .Values.etl.kafka.topics.transactions.replicas | quote }}
  partitions: {{ .Values.etl.kafka.topics.transactions.partitions | quote }}
  config:
    retention.ms: {{ .Values.etl.kafka.topics.transactions.retention.ms | quote }}
    retention.bytes: {{ .Values.etl.kafka.topics.transactions.retention.bytes | quote }}
    segment.bytes: 1073741824
    cleanup.policy: {{ .Values.etl.kafka.topics.transactions.cleanup.policy | quote }}
    min.cleanable.dirty.ratio: 0.5
    preallocate: true

---

apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: {{ .Values.etl.kafka.topics.logs.name | quote }}
  labels:
    strimzi.io/cluster: {{ .Values.etl.kafka.cluster_name }}
spec:
  replicas: {{ .Values.etl.kafka.topics.logs.replicas | quote }}
  partitions: {{ .Values.etl.kafka.topics.logs.partitions | quote }}
  config:
    retention.ms: {{ .Values.etl.kafka.topics.logs.retention.ms | quote }}
    retention.bytes: {{ .Values.etl.kafka.topics.logs.retention.bytes | quote }}
    segment.bytes: 1073741824
    cleanup.policy: {{ .Values.etl.kafka.topics.logs.cleanup.policy | quote }}
    min.cleanable.dirty.ratio: 0.5
    preallocate: true

{{- end }}