{{- if and (.Values.etl.mode "stream") (.Values.etl.kafka.strimzi_enabled ) }}

apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: {{ .Values.etl.kafka.topics.blocks | quote }}
  labels:
    strimzi.io/cluster: {{ .Values.etl.kafka.cluster_name }}
spec:
  replicas: 3
  partitions: 12
  config:
    retention.ms: -1
    retention.bytes: -1
    segment.bytes: 1073741824
    cleanup.policy: delete
    min.cleanable.dirty.ratio: 0.5
    preallocate: true

---

apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: {{ .Values.etl.kafka.topics.transactions | quote }}
  labels:
    strimzi.io/cluster: {{ .Values.etl.kafka.cluster_name }}
spec:
  replicas: 3
  partitions: 12
  config:
    retention.ms: -1
    retention.bytes: -1
    segment.bytes: 1073741824
    cleanup.policy: delete
    min.cleanable.dirty.ratio: 0.5
    preallocate: true

---

apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: {{ .Values.etl.kafka.topics.logs | quote }}
  labels:
    strimzi.io/cluster: {{ .Values.etl.kafka.cluster_name }}
spec:
  replicas: 3
  partitions: 12
  config:
    retention.ms: -1
    retention.bytes: -1
    segment.bytes: 1073741824
    cleanup.policy: delete
    min.cleanable.dirty.ratio: 0.5
    preallocate: true

{{- end }}