deployment:
  annotations: null
  replicas: 1
  resources:
    requests:
      cpu:
      memory:
    limits:
      cpu:
      memory:
  storage:
    size:

image:
  repository: geometrylabs/iconetl
  tag: latest
  imagePullPolicy: IfNotPresent

etl:
  mode: stream
  output:
  lag:
  providerURI:
  startBlock:
  startAtHead: true
  entityTypes:
  periodSeconds: 1
  batchSize: 100
  blockBatchSize: 100
  maxWorkers:
  kafka:
    cluster_name:
    strimzi_enabled: false
    topics:
      blocks:
        name: blocks_raw
        replicas: 3
        partitions: 12
        retention:
          ms: -1
          bytes: -1
        cleanup:
          policy: compact

      transactions:
        name: transactions_raw
        replicas: 3
        partitions: 12
        retention:
          ms: -1
          bytes: -1
        cleanup:
          policy: compact

      logs:
        name: logs_raw
        replicas: 3
        partitions: 12
        retention:
          ms: -1
          bytes: -1
        cleanup:
          policy: compact

    compressionType:
    schemaRegistryURL:
    valuesAsHex: true

service:
  port: 9401
  type: ClusterIP