deployment:
  replicas: 1
  resources:
    requests:
      cpu:
      memory:
    limits:
      cpu:
      memory:
  storage:
    size:

image:
  repository: geometrylabs/iconetl
  tag: latest
  imagePullPolicy: IfNotPresent

etl:
  mode: stream
  output:
  lag:
  providerURI: https://icon.geometry-dev.net/api/v3
  startBlock:
  startAtHead: true
  entityTypes:
  periodSeconds: 1
  batchSize: 100
  blockBatchSize: 100
  maxWorkers:
  kafka:
    topics:
      blocks: blocks-mainnet-v1
      transactions: transactions-mainnet-v1
      logs: logs-mainnet-v1
    compressionType:
    schemaRegistryURL:
    valuesAsHex: true
